export const forecast = {
    "latitude": 38.97844529999999,
    "longitude": -76.4921829,
    "timezone": "America/New_York",
    "offset": -4,
    "currently": {
        "time": 1470857637,
        "summary": "Mostly Cloudy",
        "icon": "partly-cloudy-day",
        "nearestStormDistance": 55,
        "nearestStormBearing": 10,
        "precipIntensity": 0,
        "precipProbability": 0,
        "temperature": 89.52,
        "apparentTemperature": 98.44,
        "dewPoint": 73.67,
        "humidity": 0.6,
        "windSpeed": 9.31,
        "windBearing": 186,
        "visibility": 10,
        "cloudCover": 0.67,
        "pressure": 1021.13,
        "ozone": 286.14
    },
    "minutely": {
        "summary": "Mostly cloudy for the hour.",
        "icon": "partly-cloudy-day",
        "data": [
            {
                "time": 1470857580,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470857640,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470857700,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470857760,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470857820,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470857880,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470857940,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470858000,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470858060,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470858120,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470858180,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470858240,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470858300,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470858360,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470858420,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470858480,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470858540,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470858600,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470858660,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470858720,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470858780,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470858840,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470858900,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470858960,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470859020,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470859080,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470859140,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470859200,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470859260,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470859320,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470859380,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470859440,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470859500,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470859560,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470859620,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470859680,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470859740,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470859800,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470859860,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470859920,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470859980,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470860040,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470860100,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470860160,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470860220,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470860280,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470860340,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470860400,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470860460,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470860520,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470860580,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470860640,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470860700,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470860760,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470860820,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470860880,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470860940,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470861000,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470861060,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470861120,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1470861180,
                "precipIntensity": 0,
                "precipProbability": 0
            }
        ]
    },
    "hourly": {
        "summary": "Rain this evening and tomorrow morning.",
        "icon": "rain",
        "data": [
            {
                "time": 1470855600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0014,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperature": 89.64,
                "apparentTemperature": 99.01,
                "dewPoint": 74.04,
                "humidity": 0.6,
                "windSpeed": 9.27,
                "windBearing": 187,
                "visibility": 10,
                "cloudCover": 0.85,
                "pressure": 1021.61,
                "ozone": 286.63
            },
            {
                "time": 1470859200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0009,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 89.42,
                "apparentTemperature": 98.01,
                "dewPoint": 73.38,
                "humidity": 0.59,
                "windSpeed": 9.33,
                "windBearing": 186,
                "visibility": 10,
                "cloudCover": 0.53,
                "pressure": 1020.77,
                "ozone": 285.76
            },
            {
                "time": 1470862800,
                "summary": "Drizzle",
                "icon": "rain",
                "precipIntensity": 0.0081,
                "precipProbability": 0.35,
                "precipType": "rain",
                "temperature": 88.84,
                "apparentTemperature": 96.68,
                "dewPoint": 72.82,
                "humidity": 0.59,
                "windSpeed": 9.89,
                "windBearing": 185,
                "visibility": 10,
                "cloudCover": 0.76,
                "pressure": 1020.37,
                "ozone": 285.11
            },
            {
                "time": 1470866400,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0501,
                "precipProbability": 0.57,
                "precipType": "rain",
                "temperature": 87.44,
                "apparentTemperature": 95.5,
                "dewPoint": 73.47,
                "humidity": 0.63,
                "windSpeed": 8.53,
                "windBearing": 182,
                "visibility": 10,
                "cloudCover": 0.73,
                "pressure": 1019.98,
                "ozone": 284.88
            },
            {
                "time": 1470870000,
                "summary": "Rain",
                "icon": "rain",
                "precipIntensity": 0.0676,
                "precipProbability": 0.6,
                "precipType": "rain",
                "temperature": 85.31,
                "apparentTemperature": 93.28,
                "dewPoint": 74.24,
                "humidity": 0.7,
                "windSpeed": 7.39,
                "windBearing": 170,
                "visibility": 9.71,
                "cloudCover": 0.7,
                "pressure": 1019.64,
                "ozone": 284.86
            },
            {
                "time": 1470873600,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0285,
                "precipProbability": 0.52,
                "precipType": "rain",
                "temperature": 83.88,
                "apparentTemperature": 91.73,
                "dewPoint": 74.92,
                "humidity": 0.75,
                "windSpeed": 7.42,
                "windBearing": 170,
                "visibility": 9.33,
                "cloudCover": 0.7,
                "pressure": 1019.48,
                "ozone": 284.79
            },
            {
                "time": 1470877200,
                "summary": "Drizzle",
                "icon": "rain",
                "precipIntensity": 0.0063,
                "precipProbability": 0.25,
                "precipType": "rain",
                "temperature": 82.81,
                "apparentTemperature": 90.22,
                "dewPoint": 75.23,
                "humidity": 0.78,
                "windSpeed": 7.69,
                "windBearing": 168,
                "visibility": 9.1,
                "cloudCover": 0.73,
                "pressure": 1019.54,
                "ozone": 284.48
            },
            {
                "time": 1470880800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0011,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 82.1,
                "apparentTemperature": 89,
                "dewPoint": 75.24,
                "humidity": 0.8,
                "windSpeed": 8.11,
                "windBearing": 168,
                "visibility": 9.02,
                "cloudCover": 0.79,
                "pressure": 1019.81,
                "ozone": 284.12
            },
            {
                "time": 1470884400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 81.75,
                "apparentTemperature": 88.48,
                "dewPoint": 75.43,
                "humidity": 0.81,
                "windSpeed": 7.84,
                "windBearing": 170,
                "visibility": 8.98,
                "cloudCover": 0.83,
                "pressure": 1020.03,
                "ozone": 283.97
            },
            {
                "time": 1470888000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0011,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 81.06,
                "apparentTemperature": 87.15,
                "dewPoint": 75.35,
                "humidity": 0.83,
                "windSpeed": 7.31,
                "windBearing": 175,
                "visibility": 8.92,
                "cloudCover": 0.9,
                "pressure": 1020.13,
                "ozone": 284.31
            },
            {
                "time": 1470891600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.002,
                "precipProbability": 0.05,
                "precipType": "rain",
                "temperature": 80.58,
                "apparentTemperature": 86.1,
                "dewPoint": 75.15,
                "humidity": 0.84,
                "windSpeed": 6.87,
                "windBearing": 176,
                "visibility": 8.86,
                "cloudCover": 0.72,
                "pressure": 1020.17,
                "ozone": 284.88
            },
            {
                "time": 1470895200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0029,
                "precipProbability": 0.08,
                "precipType": "rain",
                "temperature": 79.88,
                "apparentTemperature": 79.88,
                "dewPoint": 74.83,
                "humidity": 0.85,
                "windSpeed": 6.16,
                "windBearing": 178,
                "visibility": 8.84,
                "cloudCover": 0.67,
                "pressure": 1020.14,
                "ozone": 285.18
            },
            {
                "time": 1470898800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0036,
                "precipProbability": 0.11,
                "precipType": "rain",
                "temperature": 79.01,
                "apparentTemperature": 79.01,
                "dewPoint": 74.22,
                "humidity": 0.85,
                "windSpeed": 6.02,
                "windBearing": 181,
                "visibility": 8.86,
                "cloudCover": 0.65,
                "pressure": 1020.01,
                "ozone": 284.97
            },
            {
                "time": 1470902400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0042,
                "precipProbability": 0.14,
                "precipType": "rain",
                "temperature": 78.01,
                "apparentTemperature": 78.01,
                "dewPoint": 73.63,
                "humidity": 0.86,
                "windSpeed": 6.08,
                "windBearing": 187,
                "visibility": 8.87,
                "cloudCover": 0.66,
                "pressure": 1019.84,
                "ozone": 284.5
            },
            {
                "time": 1470906000,
                "summary": "Drizzle",
                "icon": "rain",
                "precipIntensity": 0.0051,
                "precipProbability": 0.19,
                "precipType": "rain",
                "temperature": 77.24,
                "apparentTemperature": 77.24,
                "dewPoint": 72.79,
                "humidity": 0.86,
                "windSpeed": 5.43,
                "windBearing": 191,
                "visibility": 8.88,
                "cloudCover": 0.39,
                "pressure": 1019.75,
                "ozone": 283.96
            },
            {
                "time": 1470909600,
                "summary": "Drizzle",
                "icon": "rain",
                "precipIntensity": 0.0061,
                "precipProbability": 0.24,
                "precipType": "rain",
                "temperature": 76.67,
                "apparentTemperature": 76.67,
                "dewPoint": 72.52,
                "humidity": 0.87,
                "windSpeed": 5.28,
                "windBearing": 198,
                "visibility": 8.89,
                "cloudCover": 0.55,
                "pressure": 1019.85,
                "ozone": 283.37
            },
            {
                "time": 1470913200,
                "summary": "Drizzle",
                "icon": "rain",
                "precipIntensity": 0.0073,
                "precipProbability": 0.3,
                "precipType": "rain",
                "temperature": 77.36,
                "apparentTemperature": 77.36,
                "dewPoint": 73,
                "humidity": 0.86,
                "windSpeed": 5.28,
                "windBearing": 199,
                "visibility": 8.9,
                "cloudCover": 0.64,
                "pressure": 1020.04,
                "ozone": 282.72
            },
            {
                "time": 1470916800,
                "summary": "Drizzle",
                "icon": "rain",
                "precipIntensity": 0.009,
                "precipProbability": 0.4,
                "precipType": "rain",
                "temperature": 79.54,
                "apparentTemperature": 79.54,
                "dewPoint": 73.93,
                "humidity": 0.83,
                "windSpeed": 6.12,
                "windBearing": 205,
                "visibility": 9.25,
                "cloudCover": 0.69,
                "pressure": 1020.2,
                "ozone": 282.13
            },
            {
                "time": 1470920400,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0171,
                "precipProbability": 0.47,
                "precipType": "rain",
                "temperature": 81.07,
                "apparentTemperature": 86.93,
                "dewPoint": 74.92,
                "humidity": 0.82,
                "windSpeed": 6.26,
                "windBearing": 208,
                "visibility": 9.55,
                "cloudCover": 0.55,
                "pressure": 1020.32,
                "ozone": 281.63
            },
            {
                "time": 1470924000,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0282,
                "precipProbability": 0.51,
                "precipType": "rain",
                "temperature": 83.25,
                "apparentTemperature": 91.4,
                "dewPoint": 75.76,
                "humidity": 0.78,
                "windSpeed": 6.93,
                "windBearing": 203,
                "visibility": 9.75,
                "cloudCover": 0.56,
                "pressure": 1020.41,
                "ozone": 281.2
            },
            {
                "time": 1470927600,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0347,
                "precipProbability": 0.53,
                "precipType": "rain",
                "temperature": 85.23,
                "apparentTemperature": 95.06,
                "dewPoint": 76.17,
                "humidity": 0.74,
                "windSpeed": 7.55,
                "windBearing": 195,
                "visibility": 9.87,
                "cloudCover": 0.38,
                "pressure": 1020.36,
                "ozone": 280.86
            },
            {
                "time": 1470931200,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0286,
                "precipProbability": 0.52,
                "precipType": "rain",
                "temperature": 86.43,
                "apparentTemperature": 97.28,
                "dewPoint": 76.49,
                "humidity": 0.72,
                "windSpeed": 7.53,
                "windBearing": 189,
                "visibility": 9.93,
                "cloudCover": 0.27,
                "pressure": 1020.09,
                "ozone": 280.7
            },
            {
                "time": 1470934800,
                "summary": "Light Rain",
                "icon": "rain",
                "precipIntensity": 0.0152,
                "precipProbability": 0.45,
                "precipType": "rain",
                "temperature": 87.82,
                "apparentTemperature": 99.47,
                "dewPoint": 76.58,
                "humidity": 0.7,
                "windSpeed": 8.67,
                "windBearing": 179,
                "visibility": 10,
                "cloudCover": 0.33,
                "pressure": 1019.67,
                "ozone": 280.63
            },
            {
                "time": 1470938400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0037,
                "precipProbability": 0.12,
                "precipType": "rain",
                "temperature": 88.26,
                "apparentTemperature": 99.88,
                "dewPoint": 76.4,
                "humidity": 0.68,
                "windSpeed": 9.71,
                "windBearing": 174,
                "visibility": 10,
                "cloudCover": 0.32,
                "pressure": 1019.19,
                "ozone": 280.46
            },
            {
                "time": 1470942000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0019,
                "precipProbability": 0.04,
                "precipType": "rain",
                "temperature": 89.39,
                "apparentTemperature": 101.81,
                "dewPoint": 76.64,
                "humidity": 0.66,
                "windSpeed": 9.96,
                "windBearing": 172,
                "visibility": 10,
                "cloudCover": 0.43,
                "pressure": 1018.57,
                "ozone": 280.09
            },
            {
                "time": 1470945600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0046,
                "precipProbability": 0.16,
                "precipType": "rain",
                "temperature": 89.78,
                "apparentTemperature": 102.61,
                "dewPoint": 76.81,
                "humidity": 0.66,
                "windSpeed": 10.04,
                "windBearing": 173,
                "visibility": 10,
                "cloudCover": 0.41,
                "pressure": 1017.88,
                "ozone": 279.62
            },
            {
                "time": 1470949200,
                "summary": "Drizzle",
                "icon": "rain",
                "precipIntensity": 0.0066,
                "precipProbability": 0.26,
                "precipType": "rain",
                "temperature": 89.35,
                "apparentTemperature": 101.74,
                "dewPoint": 76.62,
                "humidity": 0.66,
                "windSpeed": 10.23,
                "windBearing": 170,
                "visibility": 10,
                "cloudCover": 0.42,
                "pressure": 1017.33,
                "ozone": 279.16
            },
            {
                "time": 1470952800,
                "summary": "Drizzle",
                "icon": "rain",
                "precipIntensity": 0.0061,
                "precipProbability": 0.24,
                "precipType": "rain",
                "temperature": 88.07,
                "apparentTemperature": 99.81,
                "dewPoint": 76.56,
                "humidity": 0.69,
                "windSpeed": 10.47,
                "windBearing": 167,
                "visibility": 10,
                "cloudCover": 0.5,
                "pressure": 1016.99,
                "ozone": 278.79
            },
            {
                "time": 1470956400,
                "summary": "Drizzle",
                "icon": "rain",
                "precipIntensity": 0.005,
                "precipProbability": 0.18,
                "precipType": "rain",
                "temperature": 86.17,
                "apparentTemperature": 96.92,
                "dewPoint": 76.52,
                "humidity": 0.73,
                "windSpeed": 10.62,
                "windBearing": 165,
                "visibility": 10,
                "cloudCover": 0.63,
                "pressure": 1016.78,
                "ozone": 278.42
            },
            {
                "time": 1470960000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0038,
                "precipProbability": 0.12,
                "precipType": "rain",
                "temperature": 84.08,
                "apparentTemperature": 93.2,
                "dewPoint": 76.21,
                "humidity": 0.77,
                "windSpeed": 10.55,
                "windBearing": 167,
                "visibility": 10,
                "cloudCover": 0.73,
                "pressure": 1016.66,
                "ozone": 277.97
            },
            {
                "time": 1470963600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0027,
                "precipProbability": 0.08,
                "precipType": "rain",
                "temperature": 82.92,
                "apparentTemperature": 91.19,
                "dewPoint": 76.21,
                "humidity": 0.8,
                "windSpeed": 10.76,
                "windBearing": 169,
                "visibility": 10,
                "cloudCover": 0.71,
                "pressure": 1016.66,
                "ozone": 277.31
            },
            {
                "time": 1470967200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0016,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperature": 82.01,
                "apparentTemperature": 89.58,
                "dewPoint": 76.3,
                "humidity": 0.83,
                "windSpeed": 11.11,
                "windBearing": 171,
                "visibility": 10,
                "cloudCover": 0.65,
                "pressure": 1016.74,
                "ozone": 276.56
            },
            {
                "time": 1470970800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0008,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 81.36,
                "apparentTemperature": 88.41,
                "dewPoint": 76.44,
                "humidity": 0.85,
                "windSpeed": 11.21,
                "windBearing": 172,
                "visibility": 10,
                "cloudCover": 0.59,
                "pressure": 1016.73,
                "ozone": 275.98
            },
            {
                "time": 1470974400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 80.92,
                "apparentTemperature": 87.75,
                "dewPoint": 76.55,
                "humidity": 0.87,
                "windSpeed": 10.72,
                "windBearing": 175,
                "visibility": 10,
                "cloudCover": 0.6,
                "pressure": 1016.53,
                "ozone": 275.73
            },
            {
                "time": 1470978000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 80.6,
                "apparentTemperature": 87.23,
                "dewPoint": 76.58,
                "humidity": 0.88,
                "windSpeed": 9.99,
                "windBearing": 180,
                "visibility": 10,
                "cloudCover": 0.62,
                "pressure": 1016.22,
                "ozone": 275.66
            },
            {
                "time": 1470981600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 80.15,
                "apparentTemperature": 86.3,
                "dewPoint": 76.43,
                "humidity": 0.88,
                "windSpeed": 9.5,
                "windBearing": 186,
                "visibility": 10,
                "cloudCover": 0.6,
                "pressure": 1015.92,
                "ozone": 275.56
            },
            {
                "time": 1470985200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0017,
                "precipProbability": 0.04,
                "precipType": "rain",
                "temperature": 79.38,
                "apparentTemperature": 79.38,
                "dewPoint": 76.03,
                "humidity": 0.9,
                "windSpeed": 9.41,
                "windBearing": 189,
                "visibility": 10,
                "cloudCover": 0.49,
                "pressure": 1015.66,
                "ozone": 275.24
            },
            {
                "time": 1470988800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0031,
                "precipProbability": 0.09,
                "precipType": "rain",
                "temperature": 78.55,
                "apparentTemperature": 78.55,
                "dewPoint": 75.53,
                "humidity": 0.91,
                "windSpeed": 9.49,
                "windBearing": 192,
                "visibility": 10,
                "cloudCover": 0.35,
                "pressure": 1015.42,
                "ozone": 274.89
            },
            {
                "time": 1470992400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0037,
                "precipProbability": 0.12,
                "precipType": "rain",
                "temperature": 77.97,
                "apparentTemperature": 77.97,
                "dewPoint": 75.1,
                "humidity": 0.91,
                "windSpeed": 9.54,
                "windBearing": 196,
                "visibility": 10,
                "cloudCover": 0.25,
                "pressure": 1015.26,
                "ozone": 274.84
            },
            {
                "time": 1470996000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0029,
                "precipProbability": 0.08,
                "precipType": "rain",
                "temperature": 77.69,
                "apparentTemperature": 77.69,
                "dewPoint": 74.78,
                "humidity": 0.91,
                "windSpeed": 9.54,
                "windBearing": 200,
                "visibility": 10,
                "cloudCover": 0.25,
                "pressure": 1015.26,
                "ozone": 275.42
            },
            {
                "time": 1470999600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0014,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperature": 78.24,
                "apparentTemperature": 78.24,
                "dewPoint": 75.1,
                "humidity": 0.9,
                "windSpeed": 9.58,
                "windBearing": 204,
                "visibility": 10,
                "cloudCover": 0.3,
                "pressure": 1015.34,
                "ozone": 276.3
            },
            {
                "time": 1471003200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 79.51,
                "apparentTemperature": 79.51,
                "dewPoint": 75.63,
                "humidity": 0.88,
                "windSpeed": 9.6,
                "windBearing": 206,
                "visibility": 10,
                "cloudCover": 0.34,
                "pressure": 1015.36,
                "ozone": 276.85
            },
            {
                "time": 1471006800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 81.63,
                "apparentTemperature": 88.7,
                "dewPoint": 76.1,
                "humidity": 0.83,
                "windSpeed": 9.44,
                "windBearing": 207,
                "visibility": 10,
                "cloudCover": 0.35,
                "pressure": 1015.28,
                "ozone": 276.7
            },
            {
                "time": 1471010400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 84.08,
                "apparentTemperature": 93.25,
                "dewPoint": 76.25,
                "humidity": 0.77,
                "windSpeed": 9.22,
                "windBearing": 206,
                "visibility": 10,
                "cloudCover": 0.36,
                "pressure": 1015.14,
                "ozone": 276.21
            },
            {
                "time": 1471014000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 86.1,
                "apparentTemperature": 96.31,
                "dewPoint": 76.08,
                "humidity": 0.72,
                "windSpeed": 9.28,
                "windBearing": 203,
                "visibility": 10,
                "cloudCover": 0.39,
                "pressure": 1014.89,
                "ozone": 275.87
            },
            {
                "time": 1471017600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 87.59,
                "apparentTemperature": 98.3,
                "dewPoint": 75.88,
                "humidity": 0.68,
                "windSpeed": 9.81,
                "windBearing": 196,
                "visibility": 10,
                "cloudCover": 0.42,
                "pressure": 1014.49,
                "ozone": 275.91
            },
            {
                "time": 1471021200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 88.89,
                "apparentTemperature": 100.01,
                "dewPoint": 75.78,
                "humidity": 0.65,
                "windSpeed": 10.66,
                "windBearing": 189,
                "visibility": 10,
                "cloudCover": 0.46,
                "pressure": 1013.99,
                "ozone": 276.1
            },
            {
                "time": 1471024800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 89.88,
                "apparentTemperature": 101.42,
                "dewPoint": 75.8,
                "humidity": 0.64,
                "windSpeed": 11.52,
                "windBearing": 183,
                "visibility": 10,
                "cloudCover": 0.44,
                "pressure": 1013.46,
                "ozone": 276.15
            },
            {
                "time": 1471028400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 90.45,
                "apparentTemperature": 102.31,
                "dewPoint": 75.89,
                "humidity": 0.63,
                "windSpeed": 12.35,
                "windBearing": 179,
                "visibility": 10,
                "cloudCover": 0.31,
                "pressure": 1012.85,
                "ozone": 275.89
            }
        ]
    },
    "daily": {
        "summary": "Light rain throughout the week, with temperatures peaking at 93°F on Sunday.",
        "icon": "rain",
        "data": [
            {
                "time": 1470801600,
                "summary": "Rain in the morning and evening.",
                "icon": "rain",
                "sunriseTime": 1470824197,
                "sunsetTime": 1470874115,
                "moonPhase": 0.25,
                "precipIntensity": 0.0135,
                "precipIntensityMax": 0.0676,
                "precipIntensityMaxTime": 1470870000,
                "precipProbability": 0.6,
                "precipType": "rain",
                "temperatureMin": 77.49,
                "temperatureMinTime": 1470805200,
                "temperatureMax": 89.64,
                "temperatureMaxTime": 1470855600,
                "apparentTemperatureMin": 77.49,
                "apparentTemperatureMinTime": 1470805200,
                "apparentTemperatureMax": 99.01,
                "apparentTemperatureMaxTime": 1470855600,
                "dewPoint": 75.12,
                "humidity": 0.79,
                "windSpeed": 6.95,
                "windBearing": 179,
                "visibility": 9.12,
                "cloudCover": 0.75,
                "pressure": 1021.21,
                "ozone": 287.43
            },
            {
                "time": 1470888000,
                "summary": "Light rain until afternoon, starting again in the evening.",
                "icon": "rain",
                "sunriseTime": 1470910653,
                "sunsetTime": 1470960442,
                "moonPhase": 0.28,
                "precipIntensity": 0.0084,
                "precipIntensityMax": 0.0347,
                "precipIntensityMaxTime": 1470927600,
                "precipProbability": 0.53,
                "precipType": "rain",
                "temperatureMin": 76.67,
                "temperatureMinTime": 1470909600,
                "temperatureMax": 89.78,
                "temperatureMaxTime": 1470945600,
                "apparentTemperatureMin": 76.67,
                "apparentTemperatureMinTime": 1470909600,
                "apparentTemperatureMax": 102.61,
                "apparentTemperatureMaxTime": 1470945600,
                "dewPoint": 75.42,
                "humidity": 0.78,
                "windSpeed": 7.98,
                "windBearing": 179,
                "visibility": 9.56,
                "cloudCover": 0.56,
                "pressure": 1018.94,
                "ozone": 281.06
            },
            {
                "time": 1470974400,
                "summary": "Partly cloudy until afternoon.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1470997108,
                "sunsetTime": 1471046768,
                "moonPhase": 0.31,
                "precipIntensity": 0.0007,
                "precipIntensityMax": 0.0037,
                "precipIntensityMaxTime": 1470992400,
                "precipProbability": 0.12,
                "precipType": "rain",
                "temperatureMin": 77.69,
                "temperatureMinTime": 1470996000,
                "temperatureMax": 90.45,
                "temperatureMaxTime": 1471028400,
                "apparentTemperatureMin": 77.69,
                "apparentTemperatureMinTime": 1470996000,
                "apparentTemperatureMax": 102.31,
                "apparentTemperatureMaxTime": 1471028400,
                "dewPoint": 75.8,
                "humidity": 0.77,
                "windSpeed": 10.26,
                "windBearing": 187,
                "visibility": 10,
                "cloudCover": 0.3,
                "pressure": 1014.02,
                "ozone": 275.72
            },
            {
                "time": 1471060800,
                "summary": "Drizzle in the afternoon.",
                "icon": "rain",
                "sunriseTime": 1471083563,
                "sunsetTime": 1471133092,
                "moonPhase": 0.34,
                "precipIntensity": 0.0014,
                "precipIntensityMax": 0.0071,
                "precipIntensityMaxTime": 1471111200,
                "precipProbability": 0.29,
                "precipType": "rain",
                "temperatureMin": 78.66,
                "temperatureMinTime": 1471082400,
                "temperatureMax": 92.76,
                "temperatureMaxTime": 1471118400,
                "apparentTemperatureMin": 78.66,
                "apparentTemperatureMinTime": 1471082400,
                "apparentTemperatureMax": 106.29,
                "apparentTemperatureMaxTime": 1471118400,
                "dewPoint": 75.64,
                "humidity": 0.72,
                "windSpeed": 9.45,
                "windBearing": 195,
                "visibility": 10,
                "cloudCover": 0.36,
                "pressure": 1011.93,
                "ozone": 277.66
            },
            {
                "time": 1471147200,
                "summary": "Light rain in the morning and overnight.",
                "icon": "rain",
                "sunriseTime": 1471170019,
                "sunsetTime": 1471219416,
                "moonPhase": 0.37,
                "precipIntensity": 0.0067,
                "precipIntensityMax": 0.0264,
                "precipIntensityMaxTime": 1471165200,
                "precipProbability": 0.51,
                "precipType": "rain",
                "temperatureMin": 81.37,
                "temperatureMinTime": 1471165200,
                "temperatureMax": 93.15,
                "temperatureMaxTime": 1471197600,
                "apparentTemperatureMin": 87.5,
                "apparentTemperatureMinTime": 1471165200,
                "apparentTemperatureMax": 101.99,
                "apparentTemperatureMaxTime": 1471197600,
                "dewPoint": 74.57,
                "humidity": 0.67,
                "windSpeed": 8.05,
                "windBearing": 221,
                "cloudCover": 0.63,
                "pressure": 1013.72,
                "ozone": 280.63
            },
            {
                "time": 1471233600,
                "summary": "Partly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1471256474,
                "sunsetTime": 1471305738,
                "moonPhase": 0.4,
                "precipIntensity": 0.0039,
                "precipIntensityMax": 0.0089,
                "precipIntensityMaxTime": 1471233600,
                "precipProbability": 0.39,
                "precipType": "rain",
                "temperatureMin": 79.43,
                "temperatureMinTime": 1471258800,
                "temperatureMax": 86.69,
                "temperatureMaxTime": 1471291200,
                "apparentTemperatureMin": 79.43,
                "apparentTemperatureMinTime": 1471258800,
                "apparentTemperatureMax": 90.96,
                "apparentTemperatureMaxTime": 1471291200,
                "dewPoint": 70.82,
                "humidity": 0.67,
                "windSpeed": 4.96,
                "windBearing": 293,
                "cloudCover": 0.41,
                "pressure": 1016.38,
                "ozone": 288.02
            },
            {
                "time": 1471320000,
                "summary": "Rain starting in the afternoon.",
                "icon": "rain",
                "sunriseTime": 1471342929,
                "sunsetTime": 1471392059,
                "moonPhase": 0.44,
                "precipIntensity": 0.0099,
                "precipIntensityMax": 0.061,
                "precipIntensityMaxTime": 1471402800,
                "precipProbability": 0.59,
                "precipType": "rain",
                "temperatureMin": 77.84,
                "temperatureMinTime": 1471338000,
                "temperatureMax": 87.91,
                "temperatureMaxTime": 1471370400,
                "apparentTemperatureMin": 77.84,
                "apparentTemperatureMinTime": 1471338000,
                "apparentTemperatureMax": 95.58,
                "apparentTemperatureMaxTime": 1471370400,
                "dewPoint": 72.04,
                "humidity": 0.71,
                "windSpeed": 2.16,
                "windBearing": 148,
                "cloudCover": 0.48,
                "pressure": 1018.33,
                "ozone": 284.28
            },
            {
                "time": 1471406400,
                "summary": "Light rain until afternoon, starting again in the evening.",
                "icon": "rain",
                "sunriseTime": 1471429385,
                "sunsetTime": 1471478380,
                "moonPhase": 0.47,
                "precipIntensity": 0.0175,
                "precipIntensityMax": 0.0578,
                "precipIntensityMaxTime": 1471406400,
                "precipProbability": 0.58,
                "precipType": "rain",
                "temperatureMin": 79.01,
                "temperatureMinTime": 1471431600,
                "temperatureMax": 86.35,
                "temperatureMaxTime": 1471456800,
                "apparentTemperatureMin": 79.01,
                "apparentTemperatureMinTime": 1471431600,
                "apparentTemperatureMax": 92.7,
                "apparentTemperatureMaxTime": 1471456800,
                "dewPoint": 72.98,
                "humidity": 0.76,
                "windSpeed": 2.11,
                "windBearing": 223,
                "cloudCover": 0.71,
                "pressure": 1016.75,
                "ozone": 282.76
            }
        ]
    },
    "flags": {
        "sources": [
            "darksky",
            "lamp",
            "gfs",
            "cmc",
            "nam",
            "rap",
            "rtma",
            "sref",
            "fnmoc",
            "isd",
            "nwspa",
            "madis",
            "nearest-precip"
        ],
        "darksky-stations": [
            "KLWX"
        ],
        "lamp-stations": [
            "KADW",
            "KAPG",
            "KBWI",
            "KCGS",
            "KDCA",
            "KDMH",
            "KFME",
            "KMTN",
            "KNAK"
        ],
        "isd-stations": [
            "724047-99999",
            "745945-99999",
            "994400-99999",
            "998409-99999",
            "999999-13752"
        ],
        "madis-stations": [
            "44063",
            "APAM2",
            "AT902",
            "C9692",
            "D6845",
            "D7859",
            "E0642",
            "E5391",
            "E6471",
            "E7096",
            "E7940",
            "E8466",
            "KANP",
            "KNAK",
            "KW29",
            "TPLM2"
        ],
        "units": "us"
    }
}
